# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib Seurat, .registration = TRUE
NULL

row_sum_dgcmatrix_rust <- function(x, i, rows, `_cols`) .Call(wrap__row_sum_dgcmatrix_rust, x, i, rows, `_cols`)

row_mean_dgcmatrix_rust <- function(x, i, rows, cols) .Call(wrap__row_mean_dgcmatrix_rust, x, i, rows, cols)

row_var_dgcmatrix_rust <- function(x, i, rows, cols) .Call(wrap__row_var_dgcmatrix_rust, x, i, rows, cols)

log_norm_rust <- function(x, i, p, nrows, ncols, scale_factor, display_progress) .Call(wrap__log_norm_rust, x, i, p, nrows, ncols, scale_factor, display_progress)

standardize_rust <- function(mat, display_progress) .Call(wrap__standardize_rust, mat, display_progress)

fast_cov_rust <- function(mat, center) .Call(wrap__fast_cov_rust, mat, center)

fast_cov_mats_rust <- function(mat1, mat2, center) .Call(wrap__fast_cov_mats_rust, mat1, mat2, center)

fast_rbind_rust <- function(mat1, mat2) .Call(wrap__fast_rbind_rust, mat1, mat2)

row_var_rust <- function(mat) .Call(wrap__row_var_rust, mat)

fast_exp_mean_rust <- function(x, i, p, nrows, ncols, display_progress) .Call(wrap__fast_exp_mean_rust, x, i, p, nrows, ncols, display_progress)

sparse_row_var_rust <- function(x, i, p, nrows, ncols, display_progress) .Call(wrap__sparse_row_var_rust, x, i, p, nrows, ncols, display_progress)

sparse_row_var2_rust <- function(x, i, p, nrows, ncols, mu, display_progress) .Call(wrap__sparse_row_var2_rust, x, i, p, nrows, ncols, mu, display_progress)

sparse_row_var_std_rust <- function(x, i, p, nrows, ncols, mu, sd, vmax, display_progress) .Call(wrap__sparse_row_var_std_rust, x, i, p, nrows, ncols, mu, sd, vmax, display_progress)

fast_log_vmr_rust <- function(x, i, p, nrows, ncols, display_progress) .Call(wrap__fast_log_vmr_rust, x, i, p, nrows, ncols, display_progress)

fast_sparse_row_scale_rust <- function(x, i, p, nrows, ncols, scale, center, scale_max, display_progress) .Call(wrap__fast_sparse_row_scale_rust, x, i, p, nrows, ncols, scale, center, scale_max, display_progress)

fast_sparse_row_scale_with_known_stats_rust <- function(x, i, p, nrows, ncols, mu, sigma, scale, center, scale_max, display_progress) .Call(wrap__fast_sparse_row_scale_with_known_stats_rust, x, i, p, nrows, ncols, mu, sigma, scale, center, scale_max, display_progress)

run_umi_sampling_rust <- function(x, i, p, nrows, ncols, sample_val, upsample, `_display_progress`) .Call(wrap__run_umi_sampling_rust, x, i, p, nrows, ncols, sample_val, upsample, `_display_progress`)

run_umi_sampling_per_cell_rust <- function(x, i, p, nrows, ncols, sample_val, upsample, `_display_progress`) .Call(wrap__run_umi_sampling_per_cell_rust, x, i, p, nrows, ncols, sample_val, upsample, `_display_progress`)

row_merge_matrices_rust <- function(x1, j1, p1, nrows1, ncols1, x2, j2, p2, nrows2, ncols2, mat1_rownames, mat2_rownames, all_rownames) .Call(wrap__row_merge_matrices_rust, x1, j1, p1, nrows1, ncols1, x2, j2, p2, nrows2, ncols2, mat1_rownames, mat2_rownames, all_rownames)

replace_cols_rust <- function(x, i, p, nrows, ncols, col_idx, rx, ri, rp, rnrows, rncols) .Call(wrap__replace_cols_rust, x, i, p, nrows, ncols, col_idx, rx, ri, rp, rnrows, rncols)

graph_to_neighbor_helper_rust <- function(x, i, p, nrows, ncols) .Call(wrap__graph_to_neighbor_helper_rust, x, i, p, nrows, ncols)

fast_dist_rust <- function(x, y, n) .Call(wrap__fast_dist_rust, x, y, n)

find_weights_rust <- function(cells2, distances, anchor_cells2, integration_matrix_rownames, cell_index, anchor_score, min_dist, sd, display_progress) .Call(wrap__find_weights_rust, cells2, distances, anchor_cells2, integration_matrix_rownames, cell_index, anchor_score, min_dist, sd, display_progress)

integrate_data_rust <- function(ix, ii, ip, inrows, incols, wx, wi, wp, wnrows, wncols, ex, ei, ep, enrows, encols) .Call(wrap__integrate_data_rust, ix, ii, ip, inrows, incols, wx, wi, wp, wnrows, wncols, ex, ei, ep, enrows, encols)

score_helper_rust <- function(x, i, p, nrows, ncols, query_pca, query_dists, corrected_nns, k_snn, subtract_first_nn, display_progress) .Call(wrap__score_helper_rust, x, i, p, nrows, ncols, query_pca, query_dists, corrected_nns, k_snn, subtract_first_nn, display_progress)

compute_snn_rust <- function(nn_ranked, prune) .Call(wrap__compute_snn_rust, nn_ranked, prune)

write_edge_file_rust <- function(x, i, p, nrows, ncols, filename, display_progress) .Call(wrap__write_edge_file_rust, x, i, p, nrows, ncols, filename, display_progress)

direct_snn_to_file_rust <- function(nn_ranked, prune, display_progress, filename) .Call(wrap__direct_snn_to_file_rust, nn_ranked, prune, display_progress, filename)

snn_smallest_nonzero_dist_rust <- function(x, i, p, nrows, ncols, mat, n, nearest_dist) .Call(wrap__snn_smallest_nonzero_dist_rust, x, i, p, nrows, ncols, mat, n, nearest_dist)

run_modularity_clustering_rust <- function(x, i, p, nrows, ncols, modularity_function, resolution, algorithm, n_random_starts, n_iterations, random_seed, print_output, edgefilename) .Call(wrap__run_modularity_clustering_rust, x, i, p, nrows, ncols, modularity_function, resolution, algorithm, n_random_starts, n_iterations, random_seed, print_output, edgefilename)

# nolint end
